// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wxujbshqdlfstimectxh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind4dWpic2hxZGxmc3RpbWVjdHhoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzkyODk0OTAsImV4cCI6MjA5NDg2NTQ5MH0.Ukl_YFxYehI1kX5iDEYhNmgX9w9myfDwu16teFS9kww";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});